[database]
uri = "mongodb://localhost/liqualitytest"
debug = false

[redis]
uri = "redis://localhost:6379/1"

[application]
apiPort = 3030
queuePassword = "test123"
queuePasswordRW = "secretRWTest123"
quoteExpirationInSeconds = 43200
nodeSwapExpirationDurationInSeconds = 43200
swapExpirationDurationInSeconds = 86400

[auth]
cookieSecret = '58da74ef560e5578cb46219b7818d7c2'
cookieMaxAgeMs = 86400000
simplePassword = '25ec02267950f537347b4a7c02b00ced'

[threshold]
manualAboveFromAmountUsd = 5000

# [vault]
# endpoint = "http://127.0.0.1:8200"
# mnemonicsBasePath = "secret/data/agent/mainnet/production/mnemonics"

[worker]
minConcurrentSwaps = 3
killswitch = 'pm2 stop "Worker"'

[assets]
  [assets.BTC]
  network = "bitcoin_testnet"
  addressType = "bech32"
  swapMode = "p2wsh"
  feeNumberOfBlocks = 2
  blockTimeInSeconds = 5
  defaultFee = "average"
    [assets.BTC.wallet]
    type = "js"
    mnemonic = "snack country horror material trash seven fossil slim pet soft impose priority"
    [assets.BTC.api]
    url = "https://electrs-testnet-api.liq-chainhub.net/"
    [assets.BTC.batchApi]
    url = "https://electrs-batch-testnet-api.liq-chainhub.net/"

  [assets.YAC]
  network = "yacoin_testnet"
  feeNumberOfBlocks = 1
  blockTimeInSeconds = 5
  defaultFee = "average"
    [assets.YAC.wallet]
    type = "js"
    mnemonic = "snack country horror material trash seven fossil slim pet soft impose priority"
    [assets.YAC.api]
    esploraUrl = "http://localhost:3001/api"
    esploraSwapUrl = "http://localhost:3001"

  [assets.ETH]
  network="ropsten"
  blockTimeInSeconds = 5
  defaultFee = "average"
    [assets.ETH.wallet]
    type = "js"
    mnemonic = "snack country horror material trash seven fossil slim pet soft impose priority"
    [assets.ETH.scraper]
    url = "http://localhost:8080"
    [assets.ETH.rpc]
    url = "https://ropsten.infura.io/v3/37efa691ffec4c41a60aa4a69865d8f6"

  [assets.FAU]
  network="ropsten"
  type = "erc20"
  blockTimeInSeconds = 5
  contractAddress = "0xFab46E002BbF0b4509813474841E0716E6730136"
  defaultFee = "average"
    [assets.FAU.wallet]
    type = "js"
    mnemonic = "snack country horror material trash seven fossil slim pet soft impose priority"
    [assets.FAU.scraper]
    url = "http://localhost:8080"
    [assets.FAU.rpc]
    url = "https://ropsten.infura.io/v3/37efa691ffec4c41a60aa4a69865d8f6"
