[database]
uri = "mongodb://localhost/agentmainnet"
debug = false

[redis]
uri = "redis://localhost:6379/2"

[application]
apiPort = 3031
queuePassword = "main123"
queuePasswordRW = "secretRWMain123"
quoteExpirationInSeconds = 43200
nodeSwapExpirationDurationInSeconds = 43200
swapExpirationDurationInSeconds = 86400

[auth]
cookieSecret = '58da74ef560e5578cb46219b7818d7c2'
cookieMaxAgeMs = 86400000
simplePassword = '25ec02267950f537347b4a7c02b00ced'

[threshold]
manualAboveFromAmountUsd = 5000

# [vault]
# endpoint = "http://127.0.0.1:8200"
# mnemonicsBasePath = "secret/data/agent/mainnet/production/mnemonics"

[worker]
minConcurrentSwaps = 3
killswitch = 'pm2 stop "Worker"'

[assets]
  [assets.BTC]
  network = "bitcoin"
  addressType = "bech32"
  swapMode = "p2wsh"
  feeNumberOfBlocks = 2
  blockTimeInSeconds = 5
  defaultFee = "average"
    [assets.BTC.wallet]
    type = "js"
    mnemonic = "snack country horror material trash seven fossil slim pet soft impose priority"
    [assets.BTC.api]
    url = "https://electrs-mainnet-api.liq-chainhub.net/"
    [assets.BTC.batchApi]
    url = "https://electrs-batch-mainnet-api.liq-chainhub.net/"

  [assets.YAC]
  network = "yacoin"
  feeNumberOfBlocks = 1
  blockTimeInSeconds = 5
  defaultFee = "average"
    [assets.YAC.wallet]
    type = "js"
    mnemonic = "snack country horror material trash seven fossil slim pet soft impose priority"
    [assets.YAC.api]
    esploraUrl = "http://104.48.189.74:3001/api"
    esploraSwapUrl = "http://104.48.189.74:3001"

  [assets.ETH]
  network="ethereum_mainnet"
  blockTimeInSeconds = 5
  defaultFee = "average"
    [assets.ETH.wallet]
    type = "js"
    mnemonic = "snack country horror material trash seven fossil slim pet soft impose priority"
    [assets.ETH.scraper]
    url = "https://eth-mainnet-api.liq-chainhub.net"
    [assets.ETH.rpc]
    url = "https://mainnet.infura.io/v3/37efa691ffec4c41a60aa4a69865d8f6"

  [assets.USDT]
  network="ethereum_mainnet"
  type = "erc20"
  blockTimeInSeconds = 5
  contractAddress = "0xdac17f958d2ee523a2206206994597c13d831ec7"
  defaultFee = "average"
    [assets.USDT.wallet]
    type = "js"
    mnemonic = "snack country horror material trash seven fossil slim pet soft impose priority"
    [assets.USDT.scraper]
    url = "https://eth-mainnet-api.liq-chainhub.net"
    [assets.USDT.rpc]
    url = "https://mainnet.infura.io/v3/37efa691ffec4c41a60aa4a69865d8f6"
