[database]
uri = "mongodb://localhost/liqualitytest"
debug = false

[redis]
uri = "redis://localhost:6379/1"

[application]
apiPort = 3030
queuePassword = "test123"
queuePasswordRW = "secretRWTest123"
quoteExpirationInSeconds = 43200
nodeSwapExpirationDurationInSeconds = 43200
swapExpirationDurationInSeconds = 86400
network = "testnet"

[auth]
cookieSecret = '58da74ef560e5578cb46219b7818d7c2'
cookieMaxAgeMs = 86400000
simplePassword = '25ec02267950f537347b4a7c02b00ced'

[threshold]
manualAboveFromAmountUsd = 5000

# [vault]
# endpoint = "http://127.0.0.1:8200"
# mnemonicsBasePath = "secret/data/agent/mainnet/production/mnemonics"

[worker]
minConcurrentSwaps = 3
killswitch = 'pm2 stop "Worker"'

[assets]
  [assets.BTC]
  network = "bitcoin_testnet"
  addressType = "bech32"
  swapMode = "p2wsh"
  feeNumberOfBlocks = 2
  blockTimeInSeconds = 5
  defaultFee = "average"
    [assets.BTC.wallet]
    mnemonic = "salad wreck holiday immune example derive cause scene swim you title march"
    [assets.BTC.api]
    url = "https://mempool.space/testnet/api"
    [assets.BTC.batchApi]
    url = "https://mempool.space/testnet/api"

  [assets.YAC]
  network = "yacoin_testnet"
  feeNumberOfBlocks = 1
  blockTimeInSeconds = 5
  defaultFee = "average"
    [assets.YAC.wallet]
    mnemonic = "salad wreck holiday immune example derive cause scene swim you title march"
    [assets.YAC.api]
    esploraUrl = "http://localhost:3001/api"
    esploraSwapUrl = "http://localhost:3001"

  [assets.LTC]
  network = "litecoin_testnet"
  addressType = "bech32"
  swapMode = "p2wsh"
  feeNumberOfBlocks = 2
  blockTimeInSeconds = 5
  defaultFee = "average"
    [assets.LTC.wallet]
    mnemonic = "salad wreck holiday immune example derive cause scene swim you title march"
    [assets.LTC.api]
    url = "https://litecoinspace.org/api"
    [assets.LTC.batchApi]
    url = "https://litecoinspace.org/api"

  [assets.ETH]
  network="goerli"
  blockTimeInSeconds = 5
  defaultFee = "average"
    [assets.ETH.wallet]
    mnemonic = "salad wreck holiday immune example derive cause scene swim you title march"
    [assets.ETH.scraper]
    url = "http://localhost:8080"
    [assets.ETH.rpc]
    url = "https://goerli.infura.io/v3/37efa691ffec4c41a60aa4a69865d8f6"

  [assets.DAI]
  network="goerli"
  type = "erc20"
  blockTimeInSeconds = 5
  contractAddress = "0x11fE4B6AE13d2a6055C8D9cF65c55bac32B5d844"
  defaultFee = "average"
    [assets.DAI.wallet]
    mnemonic = "salad wreck holiday immune example derive cause scene swim you title march"
    [assets.DAI.scraper]
    url = "http://localhost:8080"
    [assets.DAI.rpc]
    url = "https://goerli.infura.io/v3/37efa691ffec4c41a60aa4a69865d8f6"
